---

- hosts: all
  become: true
  tasks:

  - name: Intall Apache and PHP for Ubuntu
    apt:
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
      update_cache: yes
